"""
AI-EVER visualizer.visualization.base.event_dispatcher — Central Event Bus

Collects animation events generated by the Visualization Manager to be sent to the frontend.
"""

from __future__ import annotations
from typing import Any, Dict, List

class EventDispatcher:
    def __init__(self):
        self._events: List[Dict[str, Any]] = []

    def dispatch(self, event_type: str, source: str, target: Any = None, metadata: Dict[str, Any] = None):
        """Dispatches an animation event."""
        event = {
            "type": event_type,
            "source": source,
            "target": target,
            "metadata": metadata or {}
        }
        self._events.append(event)

    def flush(self) -> List[Dict[str, Any]]:
        """Returns and clears all queued events."""
        events = self._events
        self._events = []
        return events
